### ISSUE TITLE
About inference time

### ISSUE THREAD

**Issue by XiongZhongxia** [wangchx67/FourLLIE#11]
Hi, thanks for your contribution！

When debugging FourLLIE, I was wondering why the checkpoint is so small but the inference time is relatively large, e.g., 0.06 seconds on  3090 GPU. Is there anyway to accelerate your model？

Thanks

**Comment by wangchx67** [comment]
I think the FFT is not a GPU-friendly operation, if you test in CPU, the inference time of FourLLIE may have advantages compared with other methods. You can try to accelerate FFT.

**Comment by XiongZhongxia** [comment]
> I think the FFT is not a GPU-friendly operation, if you test in CPU, the inference time of FourLLIE may have advantages compared with other methods. You can try to accelerate FFT.

Thanks bro
