### ISSUE TITLE
Discrepancies between the code and the paper

### ISSUE THREAD

**Issue by Maydaybye** [wangchx67/FourLLIE#14]
Thank you for your great work, but I still got some problem in the code you supplied.
Why is spatial set to True as illustrate below
![image](https://github.com/wangchx67/FourLLIE/assets/75834797/2ca015a5-63f7-4b81-b190-2b8b23390d05)
It is not concatenated with SPBlock in the paper
![image](https://github.com/wangchx67/FourLLIE/assets/75834797/eb081fb7-0cee-4742-b761-5d8bb525467c)
Should I set spatial to false in order to be consistent with the paper?

**Comment by wangchx67** [comment]
You can just follow the setting of code, since the spatial concatenation is beneficial in the frequency stage based on our experiments. However, if the spatial is set to false, the network still works.

**Comment by Maydaybye** [comment]
Understood. Thank you for your patient answer!
