### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GaoTianWL** [wangchx67/FourLLIE#2]
您好！我复现时候，指标无法达到论文所示，您可否提供一下您的训练设置，如果有预训练模型将更好，非常感谢！820072494@qq.com 邮箱

**Comment by GaoTianWL** [comment]
> _未提供描述。_

**Comment by bywlzts** [comment]
> 您好！我复现时候，指标无法达到论文所示，您可否提供一下您的训练设置，如果有预训练模型将更好，非常感谢！[820072494@qq.com](mailto:820072494@qq.com) 邮箱

你好，请问你复现出来了吗

**Comment by wangchx67** [comment]
我给你们发一份 我好像有些设置没给对  我修改一下

**Comment by wangchx67** [comment]
> > 您好！我复现时候，指标无法达到论文所示，您可否提供一下您的训练设置，如果有预训练模型将更好，非常感谢！[820072494@qq.com](mailto:820072494@qq.com) 邮箱
> 
> 你好，请问你复现出来了吗

请问可以留个邮箱吗

**Comment by bywlzts** [comment]
> 我给你们发一份 我好像有些设置没给对 我修改一下

感谢回复，bywl_zts@163.com我的邮箱

**Comment by GaoTianWL** [comment]
您好！可以发一下您的在huawei数据集训练时的配置吗？非常感谢 820072494@qq.com

**Comment by CharlesYTJ** [comment]
您好，请问您可以分享一份LOL和LSRW数据集的配置文件吗？代码里的配置文件好像有问题

Charlesjyt@163.com

感谢
