### ISSUE TITLE
Missing latest_G.pth

### ISSUE THREAD

**Issue by tahirrasheeed** [wangchx67/FourLLIE#3]
I am getting the following error while reproducing the results. 

FileNotFoundError: [Errno 2] No such file or directory: './experiments/train/models/latest_G.pth'

Kindly upload the trained model "latest_G.pth" on your repository or send it to me (email:   tahir@email.szu.edu.cn). Thanks

**Comment by xiaohan1234567** [comment]
兄弟回你了吗

**Comment by wangchx67** [comment]
We have updated the pre-trained models
