### ISSUE TITLE
t-SNE 的图

### ISSUE THREAD

**Issue by cs-hao** [wangchx67/FourLLIE#4]
同学，你好，我想咨询一下，您的Figure 1中的（b）图代码能提供么，最近赶论文需要借用一下，谢谢~

**Comment by wangchx67** [comment]
[tsne_fourier.zip](https://github.com/wangchx67/FourLLIE/files/13327954/tsne_fourier.zip)
仅供参考

**Comment by cs-hao** [comment]
> [tsne_fourier.zip](https://github.com/wangchx67/FourLLIE/files/13327954/tsne_fourier.zip) 仅供参考

thanks，我将会在最新论文中引用你的文章
