### ISSUE TITLE
关于 t-sne

### ISSUE THREAD

**Issue by SydCS** [wangchx67/FourLLIE#8]
请问能给出生成t-sne文件夹下，那五类图片的脚本文件吗，谢谢！
`img_path = "C:/Users\Dell\Desktop\mm23_fourier/tsne\input"`

**Comment by wangchx67** [comment]
https://drive.google.com/file/d/1tHzUTv-CAlSukeDnLGkRUgeA0ogt2D02/view?usp=drive_link
